services:
  postgres:
    container_name: vh_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432" # external port that we will be using : container port
    networks:
      - videohosting-net
    restart: unless-stopped

  pgadmin:
    container_name: vh_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - /var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - videohosting-net
    restart: unless-stopped



networks:
  videohosting-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
